import type { LoyaltyDashboardDemoState } from "@/lib/loyalty/types";

export const loyaltyDashboardDemoState: LoyaltyDashboardDemoState = {
  card: {
    enabled: true,
    brandName: "برندكسا كافيه",
    cardTitle: "بطاقة الولاء",
    subtitle: "اجمع الأختام واستبدل مكافأتك بسهولة",
    rewardTitle: "مشروب مجاني عند اكتمال البطاقة",
    supportingText: "بطاقة رقمية واضحة للعميل والكاشير مع باركود ورمز QR.",
    stampLabel: "ختم",
    terms: "تطبق شروط العلامة على المكافآت والاستبدال.",
    stampsRequired: 8,
    completedStamps: 5,
    cardBackground: "#4A281D",
    cardForeground: "#FCF8F3",
    cardAccent: "#D9A33F",
    logoRemoveLightBackground: true,
    logoBackgroundTolerance: 24,
    logoPlacement: "top-right",
    logoSize: 58,
    logoOffsetX: 0,
    logoOffsetY: 0,
    logoX: 74,
    logoY: 7,
    logoWidth: 15,
    logoHeight: 17,
    progressIcon: "star",
    barcodeVisible: true,
    barcodeX: 56,
    barcodeY: 66,
    barcodeWidth: 36,
    barcodeHeight: 22,
    pointsBadgeVisible: true,
    pointsBadgeX: 7,
    pointsBadgeY: 66,
    pointsBadgeWidth: 25,
    pointsBadgeHeight: 15,
    sampleCode: "BARNDAKSA-2408",
  },
  points: {
    enabled: true,
    pointValueSar: 0.25,
    minimumRedemptionPoints: 100,
    earningRule: "نقطة واحدة لكل 1 ر.س من قيمة الطلب",
    redemptionRule: "كل 100 نقطة تساوي 25 ر.س خصم",
    expiryDays: 365,
    policyText: "النقاط غير قابلة للتحويل وتظهر للعميل بعد تأكيد الطلب.",
    customerPointsBalance: 320,
    usedPoints: 80,
    earnedLastOperation: 18,
    sampleInvoiceAmount: 96,
  },
};
